apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
  namespace: hadoop
spec:
  storageClassName: hadoop-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
  namespace: hadoop
spec:
  storageClassName: hadoop-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
      </property>
    </configuration>
  hdfs-site.xml: |
    <configuration>
      <property>
        <name>dfs.replication</name>
        <value>1</value>
      </property>
      <property>
        <name>dfs.namenode.name.dir</name>
        <value>/usr/local/hadoop/data/dfs/namenode</value>
      </property>
      <property>
        <name>dfs.datanode.data.dir</name>
        <value>/usr/local/hadoop/data/dfs/datanode</value>
      </property>
    </configuration>
  yarn-site.xml: |
    <configuration>
      <property>
        <name>yarn.resourcemanager.hostname</name>
        <value>localhost</value>
      </property>
    </configuration>
  mapred-site.xml: |
    <configuration>
      <property>
        <name>mapreduce.framework.name</name>
        <value>yarn</value>
      </property>
    </configuration>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      role: namenode
  template:
    metadata:
      labels:
        app: hadoop
        role: namenode
    spec:
      containers:
        - name: hadoop-namenode
          image: docker.io/library/hadoop:latest #minikube image ls --format tabl로 가져옴
          imagePullPolicy: IfNotPresent
          env:
            - name: HADOOP_ROLE
              value: "namenode"
          ports:
            - containerPort: 9870
            - containerPort: 9000
          volumeMounts:
            - name: hadoop-config
              mountPath: /usr/local/hadoop/etc/hadoop
            - name: hadoop-data
              mountPath: /usr/local/hadoop/data
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: hadoop-data
          persistentVolumeClaim:
            claimName: hadoop-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
      role: datanode
  template:
    metadata:
      labels:
        app: hadoop
        role: datanode
    spec:
      containers:
        - name: hadoop-datanode
          image: docker.io/library/hadoop:latest #minikube image ls --format tabl로 가져옴
          imagePullPolicy: IfNotPresent
          env:
            - name: HADOOP_ROLE
              value: "datanode"
          ports:
            - containerPort: 9864
          volumeMounts:
            - name: hadoop-config
              mountPath: /usr/local/hadoop/etc/hadoop
            - name: hadoop-data
              mountPath: /usr/local/hadoop/data
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: hadoop-data
          persistentVolumeClaim:
            claimName: hadoop-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode-service
  namespace: hadoop
spec:
  selector:
    app: hadoop
    role: namenode
  ports:
    - name: namenode-http
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: namenode-rpc
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-service
  namespace: hadoop
spec:
  selector:
    app: hadoop
    role: datanode
  ports:
    - name: datanode
      protocol: TCP
      port: 9864
      targetPort: 9864
  type: NodePort
