apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
spec:
  storageClassName: hadoop-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
spec:
  storageClassName: hadoop-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
      </property>
    </configuration>
  hdfs-site.xml: |
    <configuration>
        <property>
            <name>dfs.replication</name>
            <value>1</value>
        </property>
    </configuration>

---
apiVersion: v1
kind: Pod
metadata:
  name: hadoop-pod
  labels:
    run: hadoop # Service의 selector와 일치시킵니다.
spec:
  containers:
    - name: hadoop-container
      image: docker.io/library/hadoop:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9870
        - containerPort: 9000
      volumeMounts:
        - name: hadoop-config
          mountPath: /usr/local/hadoop/etc/hadoop
        - name: hadoop-data
          mountPath: /usr/local/hadoop/data
      resources:
        requests:
          memory: "8000Mi"
          cpu: "300m"
        limits:
          memory: "12000Mi"
          cpu: "600m"
  volumes:
    - name: hadoop-config
      configMap:
        name: hadoop-config
    - name: hadoop-data
      persistentVolumeClaim:
        claimName: hadoop-pvc
