apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  selector:
    run: hadoop
  ports:
    - name: namenode-http
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: namenode-rpc
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
