apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
spec:
  storageClassName: hadoop-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
spec:
  storageClassName: hadoop-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
