apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    app: nodejs-app #pod 선택
  ports:
    - protocol: TCP
      #nodePort: 30000
      port: 31000 #kubectl port-forward service/nodejs-app 31000
      targetPort: 3002 #선택된 파드의 컨테이너 포트
  type: NodePort
