# kafka-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
