apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-service
spec:
  selector:
    app: hadoop
    role: datanode
  ports:
    - name: datanode
      protocol: TCP
      port: 9864
      targetPort: 9864
  type: NodePort
