apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-data-pv
spec:
  capacity:
    storage: 5gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hadoop/namenode-data # 네임노드 데이터 디렉토리 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-data-pv
spec:
  capacity:
    storage: 5gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hadoop/datanode-data # 데이터노드 데이터 디렉토리 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5gi
