apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode-service
spec:
  selector:
    app: hadoop
    role: namenode
  ports:
    - name: namenode-http
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: namenode-rpc
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
