apiVersion: apps/v1 # Kubernetes API 버전
kind: Deployment # 리소스 종류: Deployment

metadata: # 메타데이터 섹션 시작
  name: express-maria-deployment # 이 Deployment의 이름
  labels: # 라벨 섹션 시작
    app: express-maria-pod # 라벨: app=nodejs-app

spec: # 스펙 섹션 시작
  replicas: 1 # 배포할 파드의 수
  selector: # 선택자 섹션 시작
    matchLabels: # 일치하는 라벨 섹션 시작
      app: express-maria-pod # 선택할 파드의 라벨: app=nodejs-app
  template: # 템플릿 섹션 시작
    metadata: # 템플릿 메타데이터 섹션 시작
      labels: # 라벨 섹션 시작
        app: express-maria-pod # 파드 템플릿의 라벨: app=nodejs-app
    spec: # 템플릿 스펙 섹션 시작
      containers: # 컨테이너 섹션 시작
        - name: express-container # 컨테이너 이름: nodejs-app
          image: docker.io/library/express_db:latest #minikube image ls --format tabl로 가져옴
          imagePullPolicy: IfNotPresent
          ports: # 포트 섹션 시작
            - name: http # 포트 이름: http
              containerPort: 3000 # express/bin/www의 포트가 중요
        - name: mysql-container
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbslzhs90!
          ports:
            - name: http # 포트 이름: http
              containerPort: 3306
