apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
spec:
  containers:
    - name: nodejs-app
      image: docker.io/library/express:latest #minikube image ls --format tabl로 가져옴
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
    - name: mysql-app
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
      ports:
        - containerPort: 3306
