executor: CeleryExecutor

images:
  airflow:
    #linux
    repository: mynspluto-airflow

    #mac
    #repository: docker.io/library/mynspluto-airflow
    tag: latest

web:
  defaultUser:
    enabled: true
    username: admin
    password: admin

postgres:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow

redis:
  enabled: true
  password: redis
