apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
              name: namenode-http
          volumeMounts:
            - name: hadoop-data
              mountPath: /hadoop/data
      volumes:
        - name: hadoop-data
          persistentVolumeClaim:
            claimName: hadoop-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  selector:
    app: hadoop
  ports:
    - protocol: TCP
      port: 9870
      targetPort: 9870

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hadoop-ingress
spec:
  rules:
    - host: hadoop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hadoop-service
                port:
                  number: 9870
