apiVersion: v1
kind: Pod
metadata:
  name: hadoop-pod
  labels:
    app: hadoop
    role: namenode
spec:
  containers:
    - name: namenode
      image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
      ports:
        - containerPort: 9870
          name: namenode-http
      volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop/data
  volumes:
    - name: hadoop-data
      persistentVolumeClaim:
        claimName: hadoop-data-pvc
