apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hadoop-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-data-pvc
spec:
  volumeName: hadoop-data-pv # PV를 연결합니다.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
