apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
spec:
  storageClassName: hadoop-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/hadoop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
spec:
  storageClassName: hadoop-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
