apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark
    role: worker
  ports:
    - name: spark-worker-ui
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
