apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  kafka.properties: |
    broker.id=0
    listeners=PLAINTEXT://:9092
    log.dirs=/var/lib/kafka/data
    zookeeper.connect=localhost:2181
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    auto.create.topics.enable=true
    delete.topic.enable=true
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: zookeeper
      image: zookeeper:3.6.3
      ports:
        - containerPort: 2181
      env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: server.1=localhost:2888:3888
      volumeMounts:
        - name: zookeeper-data
          mountPath: /data
    - name: kafka
      image: confluentinc/cp-kafka:latest
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
      volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: kafka-config
          mountPath: /etc/kafka
          subPath: kafka.properties
  volumes:
    - name: zookeeper-data
      emptyDir: {}
    - name: kafka-data
      emptyDir: {}
    - name: kafka-config
      configMap:
        name: kafka-config
        items:
          - key: kafka.properties
            path: kafka.properties
