---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  ports:
    - name: kafka-1
      port: 30000
      targetPort: 29092
    - name: kafka-2
      port: 30001
      targetPort: 9092
    - name: kafka-3
      port: 31000
      targetPort: 9101
  selector:
    app: broker
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-server:7.6.1
          command:
            ["bash", "-c", "unset KAFKA_REST_PORT; /etc/confluent/docker/run"]
          ports:
            - containerPort: 9092
            - containerPort: 9101
            - containerPort: 29092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:32000"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker:30000,PLAINTEXT_HOST://broker:30001"
