apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
    - name: kafka
      image: confluentinc/cp-kafka:latest
      env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-headless:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: SASL_PLAINTEXT://localhost:29092
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
