apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-config-pv
spec:
  storageClassName: hadoop-config-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/hadoop-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-config-pvc
spec:
  storageClassName: hadoop-config-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/hadoop-hdfs/cache/hdfs/dfs/name
---
# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Namenode Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: apache/hadoop:3
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ ! -d "/var/lib/hadoop-hdfs/cache/hdfs/dfs/name/current" ]; then
                echo "Y" | hdfs namenode -format
              fi
              hdfs namenode
          ports:
            - containerPort: 9870
            - containerPort: 8020
          volumeMounts:
            - name: hdfs-name-volume
              mountPath: /var/lib/hadoop-hdfs/cache/hdfs/dfs/name
            - name: hadoop-config-volume
              mountPath: /opt/hadoop/etc/hadoop
      volumes:
        - name: hdfs-name-volume
          persistentVolumeClaim:
            claimName: namenode-pvc
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - name: web
      port: 9870
      targetPort: 9870
    - name: rpc
      port: 8020
      targetPort: 8020

---
# Datanode Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanodes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: apache/hadoop:3
          command: ["hdfs", "datanode"]
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /opt/hadoop/etc/hadoop
      volumes:
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-pvc

---
# Resourcemanager Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
        - name: resourcemanager
          image: apache/hadoop:3
          command: ["yarn", "resourcemanager"]
          envFrom:
            - configMapRef:
                name: hadoop-config
          ports:
            - containerPort: 8088
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /opt/hadoop/etc/hadoop
      volumes:
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
spec:
  # type: NodePort
  selector:
    app: resourcemanager
  ports:
    - name: web
      port: 8088
      targetPort: 8088
      # nodePort: 30000

---
# Nodemanager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemanager
  template:
    metadata:
      labels:
        app: nodemanager
    spec:
      containers:
        - name: nodemanager
          image: apache/hadoop:3
          command: ["yarn", "nodemanager"]
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /opt/hadoop/etc/hadoop/aas
      volumes:
        - name: hadoop-config-volume
          persistentVolumeClaim:
            claimName: hadoop-config-pvc
