executor: CeleryExecutor

airflow:
  image:
    repository: apache/airflow
    tag: 2.3.0

web:
  defaultUser:
    enabled: true
    username: admin
    password: admin

postgres:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow

redis:
  enabled: true
  password: redis
